server:
  port: 8769
spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#配置远程读取配置文件
#spring:
#  application:
#    name: config-server
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/xhlx/SpringcloudConfig
#          search-paths: respo
#          username: xhlx@sina.com
#          password:
#      label: master